# Generated by Django 5.1.7 on 2025-03-24 01:26

import accounts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=accounts.utils.get_random_username, max_length=255, unique=True),
        ),
    ]
