# Generated by Django 5.2 on 2025-04-19 17:10

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_google_id_user_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodePassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('expire_date', models.DateTimeField(default=datetime.datetime(2025, 4, 19, 17, 11, 11, 690652, tzinfo=datetime.timezone.utc))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_password', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
