# Generated by Django 5.2 on 2025-04-19 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_codepassword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codepassword',
            name='user',
        ),
        migrations.AddField(
            model_name='codepassword',
            name='email',
            field=models.EmailField(default='None', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='codepassword',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 19, 17, 18, 57, 612060, tzinfo=datetime.timezone.utc)),
        ),
    ]
