# Generated by Django 5.2 on 2025-04-19 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_codepassword_user_codepassword_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codepassword',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 19, 17, 23, 40, 433630, tzinfo=datetime.timezone.utc)),
        ),
    ]
