# Generated by Django 5.2 on 2025-04-22 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
        ('products', '0008_alter_category_options_alter_inventory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recentproducts',
            options={'verbose_name': 'Recent Product', 'verbose_name_plural': 'Recent Products'},
        ),
        migrations.AlterField(
            model_name='recentproducts',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='recentproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='recentproducts',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='recentproducts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_products', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
