# Generated by Django 5.2 on 2025-04-22 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_address_options_alter_codeemail_options_and_more'),
        ('orders', '0002_alter_orderdetails_product'),
        ('products', '0008_alter_category_options_alter_inventory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderdetails',
            options={'verbose_name': 'Order Detail', 'verbose_name_plural': 'Order Details'},
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_code',
            field=models.CharField(blank=True, default='None', max_length=255, null=True, verbose_name='Discount Code'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.address', verbose_name='Shipping Address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='Shipping Cost'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(max_length=50, verbose_name='Shipping Method'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('processing', 'Processing'), ('on_hold', 'On Hold'), ('packing', 'Packing'), ('shipped', 'Shipped'), ('in_delivery', 'In Delivery'), ('delivered', 'Delivered'), ('return_requested', 'Return Requested'), ('returned', 'Returned'), ('refunded', 'Refunded'), ('canceled', 'Canceled'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_product', to='products.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='quantity',
            field=models.IntegerField(verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
