name: CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
jobs:
    build:
        if: github.actor != 'github-actions[bot]'
        runs-on: ubuntu-latest
        services:
            postgres:
                image: postgres:16
                env:
                    POSTGRES_DB: test_db
                    POSTGRES_USER: test_user
                    POSTGRES_PASSWORD: test_password
                ports:
                    - 5432:5432
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
            redis:
                image: redis:7-alpine
                ports:
                    - 6379:6379
                options: >-
                    --health-cmd "redis-cli ping"
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
        env:
            SECRET_KEY: test
            DEBUG: True
            DB_NAME: test_db
            DB_USER: test_user
            DB_PASSWORD: test_password
            DB_HOST: localhost
            DB_PORT: 5432
            REDIS_HOST: localhost
            REDIS_PORT: 6379
            CELERY_BROKER_URL: redis://localhost:6379/0
            CELERY_RESULT_BACKEND: redis://localhost:6379/0
            TIMEZONE: ${{ secrets.TIMEZONE }}

            EMAIL_BACKEND: ${{ secrets.EMAIL_BACKEND }}
            EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
            EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
            EMAIL_USE_TLS: ${{ secrets.EMAIL_USE_TLS }}
            EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
            EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}

            AUTH_USER_MODEL: 'accounts.User'

            USE_TZ: True
            GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
            GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
            GOOGLE_REDIRECT_URI: ${{ secrets.GOOGLE_REDIRECT_URI }}
            GOOGLE_AUTH_URL: ${{ secrets.GOOGLE_AUTH_URL }}
            GOOGLE_TOKEN_URL: ${{ secrets.GOOGLE_TOKEN_URL }}
            GOOGLE_USER_INFO_URL: ${{ secrets.GOOGLE_USER_INFO_URL }}
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.13
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
            - name: Run tests
              run: |
                  python manage.py test
