# Generated by Django 5.1.7 on 2025-03-30 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_inventory_product_inventory_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='inventory',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.inventory'),
        ),
    ]
