# Generated by Django 5.2 on 2025-04-06 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='full_description',
            field=models.TextField(blank=True, help_text='Detailed product description with marketing tone.', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='key_features',
            field=models.JSONField(blank=True, default=list, help_text='List of key features.', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, default='None description', help_text='Short catchy description for the product page.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.JSONField(blank=True, default=dict, help_text='Key-value technical specs.', null=True),
        ),
    ]
