# Generated by Django 5.2 on 2025-04-06 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_description_product_full_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='key_features',
            field=models.TextField(blank=True, default=list, help_text='List of key features.', null=True),
        ),
    ]
