# Generated by Django 5.2 on 2025-04-06 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_key_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='key_features',
            field=models.TextField(blank=True, help_text='List of key features.', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.TextField(blank=True, help_text='Key-value technical specs.', null=True),
        ),
    ]
