# Generated by Django 5.2 on 2025-05-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_category_options_alter_inventory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='name',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='reserved_quantity',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='stock_count',
        ),
        migrations.AddField(
            model_name='product',
            name='stock_count',
            field=models.IntegerField(default=0, verbose_name='Stock Count'),
            preserve_default=False,
        ),
    ]
